// eslint-disable-next-line import/no-anonymous-default-export
export default {
  // FONT
  FONT_SIZE_EXTRA_SMALL: 12,
  FONT_SIZE_SMALL: 14,
  FONT_SIZE_NORMAL: 16,
  FONT_SIZE_MEDIUM: 18,
  FONT_SIZE_LARGE: 20,
  FONT_SIZE_EXTRA_LARGE: 22,

  // FONT FAMILY
  FONG_FAMILY: null,

  // COLORS
  PRIMARY_COLOR: '#0061FE',
  LIGHT_PRIMARY_COLOR: '#0061FE90',
  WHITE_COLOR: '#fcfbfb',
  SECOND_WHITE_COLOR: '#FBE9E770',
  BLACK_COLOR: '#110F0F',
  LIGHT_BLACK_COLOR: '#110F0F90',

  LIGHT_COLOR: '#F0EEEB',
  GREY_COLOR: '#CDC3BA',
  DANGER_COLOR: '#d91e18',

  // WEIGHT
  FONT_WEIGHT_LIGHT: '500',
  FONT_WEIGHT_MEDIUM: '700',
  FONT_WEIGHT_HEAVY: 'bold',

  // BORDER RADIUS
  IMAGE_BORDER_RADIUS: 5,
  BUTTON_BORDER_RADIUS: 8,
  PROFILE_IMAGE_BORDER_RADIUS: 99,
};
